apiVersion: v1
data:
  tls.crt: "{{ lookup('ansible.builtin.file', ingress.certificate_file) | b64encode }}"
  tls.key: "{{ lookup('ansible.builtin.file', ingress.private_key_file) | b64encode }}"
kind: Secret
metadata:
  creationTimestamp: null
  name: czertainly-ingress-tls
  namespace: czertainly
type: kubernetes.io/tls
